algoritmo "Area e Perimetro Retangulo"
// Função : calcular area e perimetro
// Autor : beatriz
// Data : 12/02/2020
// Seção de Declarações 
var
b,h,p,a:real
inicio
// Seção de Comandos 
escreval("Indique a largura do retângulo:")
leia(b)
escreval("Indique a altura do retângulo:")
leia(h)
//processamento
a<-(b*h)
p<-(2*b)+(2*H)
//saida
escreval("A area do retângulo é",a)
escreval("O perimetro do retângulo é",p)
fimalgoritmo
