algoritmo "Volei"
// Função : verificar se o jogador pode participar do campeonato
// Autor :
// Data : 06/06/2020
// Seção de Declarações 
var
altura, idade:real

inicio
// Seção de Comandos 
escreval("Qual a sua idade?")
leia(idade)
escreval ("Qual a sua altura?")
leia (altura)

se (idade>17)e(altura>=1.75)entao
    escreval("De acordo com suas respostas você pode competir!!!")
senao
    escreval("De acordo com suas respostas você infelizmente pode competir ;-;")
fimse

fimalgoritmo
