algoritmo "areadotriangulo"
// Função : calculararea
// Autor : Beatriz
// Data : 11/02/2020
// Seção de Declarações 
var
a,b,h:real
inicio
// Seção de Comandos 
escreval("indique em centimetros a base do triangulo:")
leia(b)
escreval("indique em centimetros a altura do triangulo:")
leia(a)
//processamento
r<-(b*a)/2
//saida
escreval("a area do tringulo é:")
leia(r)

fimalgoritmo
