algoritmo "3- numeros impares"
// Função : mostrar ao usuario os numeros impares contidos entre 100 e 200
// Autor : Beatriz Pereira
// Data : 26/08/2020
// Seção de Declarações 
var
cont:inteiro

inicio
// Seção de Comandos 
escreval ("-----------Numeros Impares entre 100 e 200---------")
para cont de 101 ate 200 passo 2 faca
     escreval (cont)
fimpara
escreval ("---------------------------------------------------")
fimalgoritmo
