algoritmo "carrinho 1"
// Função : decidir se a pessoa pode dirigir
// Autor : Beatriz Pereira
// Data : 18/06/2020
// Seção de Declarações 
var
idade: inteiro
inicio
// Seção de Comandos 
escreval ("qual a sua idade:")
leia (idade)
//decisão
se (idade>=18) entao
       escreval("Pode passar!")
senao
       escreval("Não pode passar!Você é menor de idade!!!")
         
fimse
fimalgoritmo
